apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: example
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      annotations:

      labels:
        app: example
    spec:
      containers:
      - name: example
        image: example:1.0
        ports:
        - name: http
          containerPort: 8080
